version: '3.8'

services:
  flask:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: